### ISSUE TITLE
Deviation from the paper

### ISSUE THREAD

**Issue by newhoggy** [Gabriel439/Haskell-Succinct-Vector-Library#1]
Hi Gabriel,

I just noticed that you commented "TODO: Explain the deviation from the paper here" in your source code.

Would you be able to explain what that's about?

Cheers,

-John

**Comment by Gabriel439** [comment]
So I like I mentioned in #2 I will be switching to a different algorithm, but I'll still explain why I deviated from the paper at this part.

This code in question is related to the section titled "Selecting over the bit array".  Near the end of that section is the algorithm for creating the secondary inventory.  The algorithm as written is correct, but inefficient for the case of `2 <= s < 16`  and `16 <= s < 128` because the first-level counts that you have to compute when building the index are not aligned to the first-level counts computed as part of the `rank9` data structure.  The tweak I made to the algorithm lets you reuse the first-level counts from the `rank9` data structure when building the secondary inventory in order to speed up index construction.

One of the issues with these succinct data structure papers in general is they talk a lot about how to efficiently query the index but they don't spend any time talking about how to efficiently build the index.  These papers were written with the assumption that the cost of building the index would be amortized over lots of queries.  However, the use cases that I have in mind require the index construction to also be efficient either because the data to index is massive or because the index won't be queried many times.

**Comment by newhoggy** [comment]
That is a very good explanation.  Thank you.

**Comment by Gabriel439** [comment]
You're welcome!
